# Generated by Django 6.0.6 on 2026-07-02 09:03

from django.db import migrations

def seed_data(apps, schema_editor):
    Category = apps.get_model('chopee', 'Category')
    Product = apps.get_model('chopee', 'Product')

    electronics = Category.objects.create(name='Electronics', icon='bi-laptop')
    fashion = Category.objects.create(name='Fashion', icon='bi-tags')
    home = Category.objects.create(name='Home & Living', icon='bi-house-heart')
    beauty = Category.objects.create(name='Beauty', icon='bi-heart')

    Product.objects.create(
        name="Custom RGB Mechanical Keyboard",
        description="Sleek keyboard featuring hot-swappable tactile blue switches, double-shot injection keycaps, premium aluminium top plate, and full RGB customizable backlighting presets.",
        price=1290.00,
        original_price=2500.00,
        image="keyboard.png",
        rating=4.8,
        sold_count=1240,
        location="กรุงเทพมหานคร",
        category=electronics,
        stock=15
    )

    Product.objects.create(
        name="Wireless ANC Over-Ear Headphones",
        description="Active Noise-Cancelling (ANC) headphones with high-fidelity sound, deep bass response, comfortable memory-foam earcups, and up to 40 hours of playtime on a single charge.",
        price=2490.00,
        original_price=4990.00,
        image="headphones.png",
        rating=4.9,
        sold_count=850,
        location="ต่างประเทศ",
        category=electronics,
        stock=8
    )

    Product.objects.create(
        name="AMOLED Smartwatch Pro",
        description="Stylish high-end smartwatch with a 1.43-inch AMOLED display, real-time heart rate sensor, oxygen saturation monitor, 100+ sport modes, and GPS navigation. Water-resistant up to 50 meters.",
        price=1590.00,
        original_price=3200.00,
        image="smartwatch.png",
        rating=4.7,
        sold_count=2130,
        location="สมุทรปราการ",
        category=electronics,
        stock=24
    )

    Product.objects.create(
        name="Minimalist White Urban Sneakers",
        description="Trendy low-top lifestyle sneakers made of premium breathable materials, featuring a lightweight rubber sole, orthotic support insole, and classic minimalist aesthetics. Perfect for any outfit.",
        price=790.00,
        original_price=1500.00,
        image="sneakers.png",
        rating=4.6,
        sold_count=3420,
        location="นนทบุรี",
        category=fashion,
        stock=50
    )

def clear_data(apps, schema_editor):
    Category = apps.get_model('chopee', 'Category')
    Product = apps.get_model('chopee', 'Product')
    Product.objects.all().delete()
    Category.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('chopee', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, clear_data),
    ]
